### ISSUE TITLE
Value expression support

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#163]
Do you plan add support for value expression?

**Comment by dwitry** [comment]
Hello @mad 

Cypher for Gremlin currently supports value expressions in most common places (return expressions, projections, property update...).

Do you have any specific query examples?

**Comment by mad** [comment]
CASE expression

**Comment by dwitry** [comment]
CASE expression is not implemented yet.

It should be possible to translate it to Gremlin [Choose Step](https://tinkerpop.apache.org/docs/current/reference/#choose-step).

I will take a look into this.
