### ISSUE TITLE
Multiple functions not supported for neo4j 2.3.12 

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#225]
From this https://neo4j.com/docs/2.3.12/cypher-refcard/

startNode, endNode, round, trim, substring, split

Some of implemented on https://github.com/opencypher/cypher-for-gremlin/pull/187 but not released

**Comment by dwitry** [comment]
Hello @mad,

Functions `startNode`, `endNode`, `substring` and `split` are implemented, waiting for release.

Next release is planned in mid January (may be subject to change). If possible please [build](https://github.com/opencypher/cypher-for-gremlin#development) latest version.

We will consider implementing `round` and `trim` functions after that.

**Comment by dwitry** [comment]
Implemented in #228
