### ISSUE TITLE
opencypher.gremlin could not be found

### ISSUE THREAD

**Issue by SarthakGhosh16** [opencypher/cypher-for-gremlin#254]
## Description
I'm trying to use cypher-for-gremlin but not able to use the plugin.

I followed the steps mentioned here: https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-console-plugin

After running ```gremlin> :install org.opencypher.gremlin cypher-gremlin-console-plugin 1.0.0```
It prompts me, ```==>Loaded: [org.opencypher.gremlin, cypher-gremlin-console-plugin, 1.0.0] -``` but never asks to ```restart the console to use [opencypher.gremlin]```

I checked the **/ext** folder where a folder named **cypher-gremlin-console-plugin** is formed with all the required jars inside it (inside lib and plugin folder)

plugin-info.txt file contains this: ```org.opencypher.gremlin:cypher-gremlin-console-plugin:1.0.0```

Also, at ```/root/.groovy/grapes/``` I can see a folder ```org.opencypher.gremlin``` been created.

After quitting and starting gremlin server, I am still not able to see opencypher.gremlin in the :plugin list and when I try to use it throws below attached error.
<img width="616" alt="Screenshot 2019-03-19 at 4 45 12 PM" src="https://user-images.githubusercontent.com/38001243/54601938-4b2ef900-4a66-11e9-9d33-75add4a7943d.png">

**Comment by SarthakGhosh16** [comment]
Would like to add to this issue

When I try to install the plugin again, it prompts that the plugin has already been installed

```==>a module with the name cypher-gremlin-console-plugin is already installed```

**Comment by dwitry** [comment]
Hello @SarthakGhosh16,

1. Which version of Gremlin Console are you using?
2. Can you try `:install org.opencypher.gremlin cypher-gremlin-console-plugin 0.9.13` (which should work with Gremlin Console<3.4.0)
3. Does [Gremlin Console bundled with Cypher for Gremlin](https://github.com/opencypher/cypher-for-gremlin/releases/download/v1.0.0/cypher-gremlin-console-3.4.0.zip) works for you?

**Comment by SarthakGhosh16** [comment]
Hi @dwitry 
Thanks for replying

I'm using gremlin console which comes with janusgraph v0.2.0
https://github.com/JanusGraph/janusgraph/releases/tag/v0.2.0

```bin/gremlin.sh > Gremlin.version() ==>3.2.6```

I tried ```:install org.opencypher.gremlin cypher-gremlin-console-plugin 0.9.13``` but again the console never prompts me to restart it.

<img width="964" alt="Screenshot 2019-03-20 at 2 31 40 PM" src="https://user-images.githubusercontent.com/38001243/54671846-c652e680-4b1c-11e9-84ef-e370e8b615e8.png">

The folder named ```cypher-gremlin-console-plugin``` is present in the /ext folder but ```:plugin use opencypher.gremlin``` still doesn't work for me. 

The ```:uninstall cypher-gremlin-console-plugin``` command worked which means it is able to pick the location of the plugin.

**Comment by dwitry** [comment]
Ok, so JanusGraph v0.2.0 uses TinkerPop 3.2.6 which has plugin API different than TinkerPop 3.3.x. That's why plugin is not recognized in your case. This means Cypher for Gremlin will work only with JanusGraph v0.3.0+. 

You can either upgrade JanusGraph, or use newer Console version with [translation in Console](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-console-plugin#user-content-usage). Can't guarantee that all functionality will work, because Cypher for Gremlin  was never tested with TinkerPop<3.3.1.

**Comment by SarthakGhosh16** [comment]
Ok. I'll upgrade JanusGraph to **v0.3.1** 
https://github.com/JanusGraph/janusgraph/releases/tag/v0.3.1
which uses **Apache TinkerPop** **3.3.3**. 

I'll install it and check the Gremlin version which comes along with it and then try to install ```cypher-gremlin-console-plugin```
If it works, I'll close the issue.

Thank you so much @dwitry for your help. You saved my day.

**Comment by SarthakGhosh16** [comment]
Ok. So I downloaded JanusGraph v0.3.1 which comes with Gremlin Version 3.3.3 and TinkerPop 3.3.3
At the first go itself the ```:install``` and ```:plugin use``` worked. 

Thanks again @dwitry . Closing this issue.
