### ISSUE TITLE
Support for `replace` function

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#255]

**Comment by dwitry** [comment]
Hello @mad,

I assume that you are using JanusGraph, which is not [upgraded to TinkerPop 3.4.0](https://github.com/JanusGraph/janusgraph/issues/1364) yet, so Cypher for Gremlin 1.0.0+ will not work there.

Do you need #255 to be merged to Cypher for Gremlin [branch](https://github.com/opencypher/cypher-for-gremlin/tree/tinkerpop334) that uses TinkerPop 3.3.4?

**Comment by mad** [comment]
Hello @dwitry 

Thanks, It would be good

**Comment by dwitry** [comment]
[Merged](https://github.com/opencypher/cypher-for-gremlin/commit/d94895326e324c7a701cfdeaa0761494ef4ce248) to [tinkerpop334 branch](https://github.com/opencypher/cypher-for-gremlin/tree/tinkerpop334)
