### ISSUE TITLE
Problem fetching data from amazone Neptune Db

### ISSUE THREAD

**Issue by vikaskumardixit** [opencypher/cypher-for-gremlin#270]
Creating query is working fine but when i am trying to run MATCH gremlin Throws and exception 
`java.lang.NoClassDefFoundError: org/apache/tinkerpop/gremlin/process/traversal/step/util/WithOptions
`

**Comment by dwitry** [comment]
Hello @vikaskumardixit,

`WithOptions` were [introduced](http://tinkerpop.apache.org/docs/3.4.0/upgrade/#_indexing_of_collections) in TinkerPop 3.4.0 and are not supported in AWS Neptune. 

To address this and other [Neptune specifics](https://github.com/opencypher/cypher-for-gremlin/wiki/Gremlin-implementations#neptune) use Neptune [flavor](https://github.com/opencypher/cypher-for-gremlin/wiki/Gremlin-implementations#flavors) when configuring  translation.

**Comment by vikaskumardixit** [comment]
thanks @dwitry 
its working
