### ISSUE TITLE
Multiple MATCH works is incorrect

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#278]
Example of graph

```
        graph.traversal()
             .addV("Org").property("Name", "Org1").as("org1")
             .addV("Org").property("Name", "Org2").as("org2")
             .addV("Person").property("Name", "Foo").as("p1")
             .addV("Person").property("Name", "Boo").as("p2")
             .addV("Doc").property("Title", "Doc1").as("doc")
             .addE("E").from("org1").to("p1")
             .addE("E").from("org1").to("p2")
             .addE("E").from("org2").to("p1")
             .addE("E").from("org2").to("p2")
             .addE("E").from("org1").to("doc")
             .addE("E").from("org2").to("doc")
```

And cypher query

```
MATCH (org1:Org)--(p:Person)--(org2:Org)
MATCH (org1:Org)--(doc:Doc)--(org2:Org)
WHERE id(org1) IN [{nID}] AND id(org1) <> id(org2)
RETURN p.Name AS personName, org2.Name AS orgName
```

Expected result is:

```
[{personName=Boo, orgName=Org2}, {personName=Foo, orgName=Org2}]
```

But actual is:

```
[{personName=Foo, orgName=Org2}]
```

**Comment by dwitry** [comment]
Hello @mad,

thank you for reporting this.

As Cypher query is translated to a single Gremlin traversal, there are some limitations for multiple `MATCH` clauses. First `MATCH` clause returns 2 records. Second `MATCH` clause returns 1 record. As these are in the same traversal, result count gets limited by the second clause, and only 1st record is returned (query will work correctly if  `MATCH` clauses are swapped).

You are right, this should be improved, but currently, I can't think of better translation for this case.

**Comment by mad** [comment]
Hello @dwitry 

I think multiple match should be prevent for avoid bugs until new translation method introduced

**Comment by dwitry** [comment]
Hello @mad,

Agree, it makes sense to throw an exception on multiple MATCH clauses instead of returning an incorrect result. However, there are a lot of cases where multiple MATCH queries work as expected, for example:

```cypher
MATCH (m:person {name: "marko"})
MATCH (m:person {age: 29})
MATCH (m:person)-[r1:created]->(lop:software {name: "lop"})
RETURN m
```

I will take a look if it is possible to distinguish queries that will provide an incorrect result.

**Comment by dwitry** [comment]
Hello @mad,

actually, I was wrong about multiple MATCH. _Multiple MATCH feature is working correctly._ The actual cause of this bug was incorrect handling of undirected paths.

Fix pushed to master and [tinkerpop334](https://github.com/opencypher/cypher-for-gremlin/tree/tinkerpop334).
