### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by yuzhebj** [opencypher/cypher-for-gremlin#297]
Hello,
I have a question about the translation from cypher to gremlin. I have a simple query, like "`MATCH (arch:Architecture {_id:'ARCH_ID'}) RETURN arch`". But It throws error during the translation. 

Following is the error message.
`java.lang.ClassNotFoundException:org.apache.tinkerpop.gremlin.process.traversal.step.util.WithOptions`

I think this is a very common cypher statement. Could anyone help to point out where I am wrong? Many thanks.

**Comment by dwitry** [comment]
Hello @yuzhebj,

Related question: #270. 

`WithOptions` were [introduced](http://tinkerpop.apache.org/docs/3.4.0/upgrade/#_indexing_of_collections) in TinkerPop 3.4.0 and are not supported in:

* Cloud databases like AWS Neptune and Cosmos DB. 
* Gremlin Servers that use TinkerPop < 3.4.0
	- For example, Janus Graph [upgrade to TinkerPop 3.4.0](https://github.com/JanusGraph/janusgraph/issues/1364) is not released yet

To address this:

* For cloud databases use corresponding  [flavors](https://github.com/opencypher/cypher-for-gremlin/wiki/Gremlin-implementations#flavors)
* For client-side translation use flavor that will not use `WithOptions` - `gremlinServer33x`
* For server-side translation:
	- Install [previous release](https://github.com/opencypher/cypher-for-gremlin/releases/tag/v0.9.13) of Cypher for Gremlin built for TinkerPop 3.3.4 
	- Or use [`tinkerpop334` branch](https://github.com/opencypher/cypher-for-gremlin/tree/tinkerpop334)

Please let me know if you have any other questions, or close this issue.

**Comment by yuzhebj** [comment]
@dwitry Thanks for your reply. I changed the translation library version to 0.9.13, and it works now.

**Comment by dwitry** [comment]
Welcome.
Closing issue, as @yuzhebj confirmed that it works. Please open new issue if you have additional questions.
