### ISSUE TITLE
Accessing Graphs Created using ConfiguredGraphFactory

### ISSUE THREAD

**Issue by VINAYAK179** [opencypher/cypher-for-gremlin#304]
Hello,

How can we access the graphs created using ConfiguredGraphFactory? 
Actually the problem is I have more than one graphs created using ConfiguredGraphFactory. How I can select the graph dynamically and access graph using plugin.
Currently I am getting the following error : 
java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: No such property: g for class: Script21

**Comment by dwitry** [comment]
Hello, 

if I understand your requirement correctly, you will need to use aliases for [console](http://tinkerpop.apache.org/docs/current/reference/#console-aliases):

```
:remote connect ...
:remote config alias g yourGraphName
```

And for [Java API](http://tinkerpop.apache.org/docs/current/reference/#_aliases):

```
Client gremlinClient = cluster.connect().alias(singletonMap("g", "yourGraphName"));
CypherGremlinClient cypherGremlinClient = CypherGremlinClient.plugin(gremlinClient);
...
```

**Comment by VINAYAK179** [comment]
Tried the first one getting the following error: 
java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Could not alias [g] to [graph2] as [graph2] not in the Graph or TraversalSource global bindings

**Comment by dwitry** [comment]
Hello,

does this error appear without Cypher for Gremlin plugin?

Currently, it looks like JanusGraph configuration issue.

**Comment by VINAYAK179** [comment]
Hello,

Its giving the same error without Cypher for Gremlin Plugin. I think we have make some changes in create_sample.groovy file. Can you please confirm the same.

**Comment by VINAYAK179** [comment]
Hello,
I have some questions related to janusgraph deployment on server. I tried it on janusgraph group's but no replies. Can you please help me.

**Comment by dwitry** [comment]
Hello,

This is issue tracker for Cypher for Gremlin project.

I can only provide support related to Cypher for Gremlin.

Please address questions about other projects to its respective support channels.
