### ISSUE TITLE
Translate "all" expression

### ISSUE THREAD

**Issue by bangsun** [opencypher/cypher-for-gremlin#307]
can support "all" expr translation ,for example: 
MATCH p=(n:TEST)-[r*TEST_CE]-(m:TEST1{value:$test1}) where  all (edge in relationships(p) where edge.transtime>=($frms_trans_time - $frms_time_range) and edge.transtime<= 1537977600000) return count(distinct n) =1

**Comment by dwitry** [comment]
Hello @bangsun,

it is possible to implement. We will consider implementing it in future releases, however, I can't provide a time frame for that now. Contributions are always welcome.
