### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by VINAYAK179** [opencypher/cypher-for-gremlin#308]
Hello,

JanusGraph with Cassandra as backend are installed successfully on the server. Also installed cypher to gremlin plugin at server and console side. At the start it was giving the following error: java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
After solving this error now it just gets stuck. No error and output is displayed.

The commands used are as follows:
gremlin> :remote connect opencypher.gremlin conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :remote config alias g graphName
==>g=graphName
gremlin> :> MATCH (n) RETURN n LIMIT 1

No output and no error it just gets stuck

**Comment by dwitry** [comment]
Hello @VINAYAK179,

first issue shows that you are using incompatible versions of Cypher for Gremlin and JanusGraph.  Cypher for Gremlin. JanusGraph depends on Scala 2.11 and Cypher for Gremlin on Scala 2.12.

Refer to [version compatibility table](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-server-plugin#installation) for more details.

Second issue might be related to this as well.

**Comment by VINAYAK179** [comment]
Hello,
How to uninstall the plugin from server and console, so that it can be installed again with proper versions
