### ISSUE TITLE
Generating json response

### ISSUE THREAD

**Issue by VINAYAK179** [opencypher/cypher-for-gremlin#309]
Hello,

I have successfully installed the plugin and getting the response using cypher. Is there any way so that I can generate the response in json format directly.

Thanks

**Comment by dwitry** [comment]
Hello @VINAYAK179 ,

To my knowledge, the Gremlin Client does not expose JSON response.

It is possible to [configure] Gremlin Server to support REST, but [processor] request message parameter necessary for Cypher for Gremlin to work is [not handled].

So REST will only work for Gremlin (not Cypher). The only way I can imagine to achieve this is doing [client side translation], then sending the translated query to Gremlin REST endpoint.

[configure]: http://tinkerpop.apache.org/docs/current/reference/#_connecting_via_http
[processor]: (https://github.com/opencypher/cypher-for-gremlin/blob/d3a450f029dcfb7e54768ff13b51a787e6094963/tinkerpop/cypher-gremlin-server-plugin/src/main/java/org/opencypher/gremlin/server/op/cypher/CypherOpProcessor.java#L65)
[not handled]: https://github.com/apache/tinkerpop/blob/0046f96fa4e84986bbfbaea461f382fff81e3640/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java#L351-L406
[client side translation]: https://github.com/opencypher/cypher-for-gremlin/tree/master/translation#usage

**Comment by VINAYAK179** [comment]
Hello @dwitry ,

Thank You for the answer. I understood the point of translating Cypher query to gremlin and will do it. I have some question related to query to Gremlin REST endpoint after translation. 
I will add the HTTP  socket for json response. After doing this how to query the gremlin server, can you please explain with an sample example. Also whether only adding HTTP socket to server is enough or any other additions are required. 
Note : I am using Java for connection and retrieval  the result

**Comment by dwitry** [comment]
> After doing this how to query the gremlin server, can you please explain with an sample example.

Any client for Java will do, for example [OkHttp](https://square.github.io/okhttp/):

```java
MediaType JSON = MediaType.get("application/json; charset=utf-8");

OkHttpClient okHttpClient = new OkHttpClient.Builder().build();

Request request = new Request.Builder()
    .url("http://localhost:8182")
    .post(
            RequestBody.create(JSON,"{\"gremlin\" : \"" + translatedQuery + "\"}")
    )
    .build();


Response response = okHttpClient.newCall(request).execute();

System.out.println(response.body().string());
```

> Also whether only adding HTTP socket to server is enough or any other additions are required.

Setting `channelizer` to `org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer` in server config yaml should be enough.

**Comment by VINAYAK179** [comment]
I am using ConfiguredGraphFactory to access one of multiple stored graphs are any changes needed in the above code to open the specific graph using ConfiguredGraphFactory.

**Comment by dwitry** [comment]
You may need to add [aliases](https://github.com/apache/tinkerpop/blob/6c7be04be215f7877cca12b2d681d8cd81b7fb2f/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java#L114) to request body if you are using it.

**Comment by dwitry** [comment]
Closing issue after a week of inactivity. Don't hesitate to open a new issue if you have any more questions.
