### ISSUE TITLE
addVertex for CosmosDB flavor doesn't work without return

### ISSUE THREAD

**Issue by crichey** [opencypher/cypher-for-gremlin#314]
This follwoing cypher translates as shown and does not create a vertex:

`create (n:bob {name:'awesome'}) return n `
becomes
`g.addV('bob').as('n').property(single, 'name', 'awesome').select('n').project('n').by(__.valueMap(true))`
and this DOES create the vertex.

However, the following does not create a vertex:
`create (n:bob {name:'awesome'})`
translates to
`g.addV('bob').property(single, 'name', 'awesome').barrier().limit(0)`

**Comment by dwitry** [comment]
Hello @crichey,

thank you for reporting this. This is related to latest changes in Cosmos DB. We will need to find better translation for Cypher queries that return no results in Cosmos DB.
