### ISSUE TITLE
are there some statements for test coverage

### ISSUE THREAD

**Issue by Jeremy-zgp** [opencypher/cypher-for-gremlin#336]
when I use cypher for gremlin, it seems like the coverage what I get is lower than the introduction. so I want to know the test cases you use or where I can get, thank you.

**Comment by dwitry** [comment]
Hello @Jeremy-zgp,

coverage and testing approach, as well as test reports are covered in [Language Support](https://github.com/opencypher/cypher-for-gremlin#language-support) section.

Feel free to ask if you need any additional clarifications.

**Comment by Jeremy-zgp** [comment]
@dwitry 
I appreciate it very much, thank you
