### ISSUE TITLE
Capability to select from multiple graphs hosted in one Gremlin server

### ISSUE THREAD

**Issue by zhiboz** [opencypher/cypher-for-gremlin#65]
Is it feasile to support multiple graphs in one graph database / gremlin server? Thanks!

**Comment by dwitry** [comment]
Hello Zhibo,

if you are using [Cypher Client](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-server-client#usage), you can use alias for Gremlin Client:

```
Cluster cluster = Cluster.open(configuration);
Client gremlinClient = cluster.connect().alias("g2");
CypherGremlinClient cypherGremlinClient = CypherGremlinClient.plugin(gremlinClient);
```

In [Console Cypher plugin](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-console-plugin) `:remote config alias` is not supported yet.
