### ISSUE TITLE
Graphframes?

### ISSUE THREAD

**Issue by kyprifog** [opencypher/cypher-for-gremlin#9]
I think the machinery exists to do this, but I just wanted to double check, is it possible to pull graphframes into gremlin via cypher-for-gremlin:  https://github.com/graphframes/graphframes

**Comment by disolovyov** [comment]
Hi @kyprifog 

Spark is not one of our testing targets right now, as there's a separate project called [Cypher for Apache Spark](https://github.com/opencypher/cypher-for-apache-spark) that brings Cypher support to Spark directly. It doesn't integrate with GraphFrames, but it's in the backlog.

Could you elaborate what do you mean by "pulling into Gremlin"?

**Comment by kyprifog** [comment]
Hi @disolovyov, thanks for your help, probably don't mean what you think i mean by pulling into gremlin.  Just saying importing via gremlin so we can have some more flexibility of what graph DB we actually want to use.  We are currently leaning towards JanusGraph, but for importing it might make more sense to bypass gremlin altogether and just write directly to cassandra.

**Comment by kyprifog** [comment]
Meant importing to any gremlin supported graphdb via means of gremlin.  I'm now seeing that graphframes is basically a deprecated version of cypher for apache spark, so it doesn't make sense that functionality like this would be supported moving forward.

I'll go ahead and close this.
